### ISSUE TITLE
[Crash] [1.0.2] No server support - java.lang.NoClassDefFoundError: net/minecraft/client/resources/model/Material

### ISSUE THREAD

**Issue by Cixon** [Insane96/ShieldsPlus#1]
[crash-2022-07-31_03.26.30-fml.txt](https://github.com/Insane96/ShieldsPlus/files/9228231/crash-2022-07-31_03.26.30-fml.txt)
--
--
log:
[latest.log](https://github.com/Insane96/ShieldsPlus/files/9228232/latest.log)

**Comment by Insane96** [comment]
Fixed in 1.0.3
