### ISSUE TITLE
19.4 Crash on launch

### ISSUE THREAD

**Issue by xd4rkzghost01** [Insane96/ShieldsPlus#3]
Hi ! I was trying some mod for 1.19.4 and Shield+ seems not working and crash upon startup.
I've got 156 mod install and they work perfectly but when i come to this one, the game wont load and crash (code 1)
Latest without the mod:
[latest.log](https://github.com/Insane96/ShieldsPlus/files/11538321/latest.log)

The one with Shield+ install:
[latest.log](https://github.com/Insane96/ShieldsPlus/files/11538335/latest.log)
And the Crash log
[crash-2023-05-22_21.10.41-server.txt](https://github.com/Insane96/ShieldsPlus/files/11538337/crash-2023-05-22_21.10.41-server.txt)

Also i'm using the Latest Forge loader and the latest Optifine.

**Comment by Insane96** [comment]
You need InsaneLib

Also optifine bad

**Comment by xd4rkzghost01** [comment]
Sorry, i forget to mention that i've got InsaneLib too. And i tried the 2 version available on Curseforge of Shield+. I'm now at the point to try it with older version of InsaneLib.
Saddly i knew that Optifine was very bad nowaday but i dont know how works other Graphics Mods.

**Comment by Insane96** [comment]
https://github.com/TheUsefulLists/UsefulMods/blob/main/Performance/Performance119.md
This for performance.

Also send the crashlog with InsaneLib installed and try with ShieldPlus + InsaneLib only.

**Comment by Insane96** [comment]
No further respose. Closing
