### ISSUE TITLE
[BUG?] Boot crash

### ISSUE THREAD

**Issue by SeanChengN** [Insane96/ShieldsPlus#4]
Crashes on boot, works fine without this mod.

Shields+-1.6.2-mc1.20.1.jar
InsaneLib-1.10.2-mc1.20.1.jar
**Crashlog:**
https://pastebin.com/vz1VzqcV

**Comment by Insane96** [comment]
The paste is not available

**Comment by SeanChengN** [comment]
> The paste is not available

https://github.com/SeanChengN/TempImage/blob/main/minecraft-exported-logs-2023-07-31T10-13-34.log

**Comment by Insane96** [comment]
There are many errors, and none of them mentions ShieldPlus. It' about responsive shields. Remove it, Shield Plus does the same already.
