### ISSUE TITLE
1.7.0 Update crashes on startup with a null error

### ISSUE THREAD

**Issue by Dafri84** [Insane96/ShieldsPlus#5]
Using Forge 47.2 I am getting a null error on start up, reverting back to Shield+ version 1.6.7 the game loads up normally.
Crash log attached
[crash-2023-09-21_20.35.18-fml.txt](https://github.com/Insane96/ShieldsPlus/files/12696212/crash-2023-09-21_20.35.18-fml.txt)

**Comment by Insane96** [comment]
Update insanelib
