### ISSUE TITLE
Obsolete "Fast Recovery"

### ISSUE THREAD

**Issue by JynLiam** [Insane96/ShieldsPlus#7]
When "Combat Test shield disabling" & "Lifted and Cooldown" are set to false in the config file, the "Fast Recovery" enchantement becomes obsolete. As it cannot be disabled, it lowers overhaul shield enchantment effectiveness.
- Suggestion : add an option to disable "fast recovery" enchant in config.

**Comment by Insane96** [comment]
It still has a use since the shield can go on cooldown when hit with an axe

**Comment by JynLiam** [comment]
Thank you for bringing me up this information.
