### ISSUE TITLE
[MC 1.18.2] [1.2.5] ShieldsPlus has failed to load correctly

### ISSUE THREAD

**Issue by LIPDProductionsInc** [Insane96/ShieldsPlus#8]
[latest.log](https://github.com/Insane96/ShieldsPlus/files/14829854/latest.log)
[crash-2024-04-01_20.22.43-fml.txt](https://github.com/Insane96/ShieldsPlus/files/14829866/crash-2024-04-01_20.22.43-fml.txt)

**Comment by Insane96** [comment]
You have so many mods. Reproduce it with as few as possible

**Comment by Insane96** [comment]
Seems like you're just missing InsaneLib
