### ISSUE TITLE
Compat with Caverns & Chasms

### ISSUE THREAD

**Issue by FunniMCEnthusiast** [Insane96/ShieldsPlus#9]
I wanted to suggest compatibility with the Caverns & Chasms mod, as it introduces silver and necromium gear sets, silver being an alternative to gold and necromium being an alternative to netherite. Silver shields could be equivalent to gold shields, whereas necromium shields could block six hearts like diamond shields but have a lift time/cooldown of 1.5/2.5 seconds like netherite shields

Misc suggestion but both netherite and necromium shields could have red wood similar to the hilts of their respective tools

**Comment by Insane96** [comment]
There's no plan to add compatibility with other mods in the base mod
